[package]
name = "DecryptTruck"
version = "0.1.1"
description = "Decrypt your ATS and ETS2 save games with SII_Decrypt using its DLL"
authors = ["SiberianCoffe"]
edition = "2021"

[dependencies]
libloading = "0.8.4"